# Generated by Django 5.2.6 on 2025-11-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_submission_paper_alter_submission_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='abstract',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
