# Generated by Django 5.2.6 on 2025-11-10 10:17

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0004_submission_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(help_text='Séparez par des virgules (max 10)', max_length=500, validators=[ConferenceApp.models.submission.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
