# Generated by Django 5.2.6 on 2025-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0005_alter_conference_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
