# Generated by Django 5.2.7 on 2025-10-12 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s]+$', 'Room may contain only letters, numbers and spaces')]),
        ),
    ]
