# Generated by Django 5.2.7 on 2025-10-09 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='la description doit contenir au minimum 30 caractéres')]),
        ),
    ]
