# Generated by Django 5.2.7 on 2025-10-12 20:48

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_alter_conference_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(help_text='Mots-clés séparés par des virgules (max 10).', max_length=300, validators=[ConferenceApp.models.validate_keywords_max10]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='sub_paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
