# Generated by Django 5.2.7 on 2025-10-12 21:01

import ConferenceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0004_alter_submission_keywords_alter_submission_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(default=ConferenceApp.models.generate_submission_id, editable=False, max_length=12, unique=True),
        ),
    ]
